src/flow/urls.py
from django.urls import path

from . import views

app_name = "flow"

urlpatterns = [
    path("flow/", views.index, name="index"),
    path("add_applicant/", views.add_applicant, name="add_applicant"),
    path(
        "edit_applicant/<str:applicant_id>",
        views.edit_applicant,
        name="edit_applicant",
    ),
    path(
        "add_application/<str:applicant_id>",
        views.add_application,
        name="add_application",
    ),
    path(
        "edit_application/<str:applicant_id>",
        views.edit_application,
        name="edit_application",
    ),
    path("review/<str:applicant_id>", views.review, name="review"),
    path("confirmation/", views.confirmation, name="confirmation"),
]

src/renard/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("", include("flow.urls")),
]

src/flow/models.py
from datetime import date

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from multiselectfield import MultiSelectField
from phonenumber_field.modelfields import PhoneNumberField


class Applicant(models.Model):
    id = models.AutoField(primary_key=True)
    insurance_number = models.CharField(max_length=20, default="")
    first_name = models.CharField(max_length=50)
    birth_date = models.DateField(
        null=True,
        blank=True,
        validators=[
            MinValueValidator(limit_value=date(1900, 1, 1)),
            MaxValueValidator(limit_value=date.today()),
        ],
    )
    last_name = models.CharField(max_length=50)
    street_number = models.CharField(max_length=100)
    zip_code = models.IntegerField()
    city = models.CharField(max_length=50)
    phonenumber = PhoneNumberField(blank=True, region="DE")
    email = models.EmailField(max_length=254)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Applicant data for ID {self.id} (insurance number: {self.insurance_number})"


class Application(models.Model):
    id = models.AutoField(primary_key=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    first_application = models.BooleanField()
    SERVICE_OPTIONS = (
        ("cash", "Geldleistung (Pflege durch eine Privatperson)"),
        ("service", "Sachleistung (Pflege durch einen Pflegedienst)"),
        ("combined", "Kombi-Leistung (Pflege durch Privatperson & Pflegedienst)"),
        ("partial inpatient", "Tages- oder Nachtpflege (teilstationär)"),
        ("inpatient", "dauerhafte Pflege im Pflegeheim"),
        (
            "inpatient with disability",
            "dauerhafte Pflege in einer Einrichtung für behinderte Menschen",
        ),
        ("medical aids", "Hilfsmittel"),
        ("unknown", "Das weiß ich nicht"),
    )
    selected_services = MultiSelectField(choices=SERVICE_OPTIONS, max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Applicant data for ID {self.id} (applicant ID: {self.applicant})"


class Consent(models.Model):
    id = models.AutoField(primary_key=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    data_share = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Consent data for ID {self.id} (applicant ID: {self.applicant})"

src/flow/forms.py
from django import forms

from .models import Applicant, Application, Consent


class ApplicantForm(forms.ModelForm):
    birth_date = forms.DateField(
        input_formats=["%d.%m.%Y"],  # Add custom date format (DD.MM.YYYY)
        widget=forms.DateInput(
            format="%d.%m.%Y"
        ),  # Optionally specify the input widget format
    )

    class Meta:
        model = Applicant
        fields = (
            "insurance_number",
            "first_name",
            "last_name",
            "birth_date",
            "street_number",
            "zip_code",
            "city",
            "phonenumber",
            "email",
        )
        labels = {
            "insurance_number": "Versicherungsnummer",
            "first_name": "Vorname",
            "last_name": "Nachname",
            "birth_date": "Geburtsdatum",
            "street_number": "Strasse und Hausnummer",
            "zip_code": "Postleitzahl",
            "city": "Stadt",
            "phonenumber": "Telefonnummer",
            "email": "E-Mail-Adresse",
        }


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = (
            "first_application",
            "selected_services",
        )
        labels = {
            "first_application": "Erstantrag",
            "selected_services": "Leistungen, für die der Antrag gestellt wird",
        }


class ConsentForm(forms.ModelForm):
    data_share = forms.BooleanField(
        required=True,
        label="Hiermit erteile ich die nachfolgend verlinkte Schweigepflichtentbindung und Einwilligungserklärung.",
    )

    class Meta:
        model = Consent
        fields = ("data_share",)
        labels = {
            "data_share": "Hiermit erteile ich die nachfolgend verlinkte Schweigepflichtentbindung und Einwilligungserklärung."
        }

src/flow/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import ApplicantForm, ApplicationForm, ConsentForm
from .models import Applicant, Application


def index(request: HttpRequest) -> HttpResponse:
    return render(request, template_name="flow/index.html")


def add_applicant(request: HttpRequest) -> HttpResponse:
    form = ApplicantForm(data=request.POST or None)
    if form.is_valid():
        new_applicant = form.save()
        redirect_url = reverse("flow:add_application", args=[new_applicant.id])
        return redirect(to=redirect_url)
    return render(request, "flow/add_applicant_form.html", {"form": form})


def edit_applicant(request: HttpRequest, applicant_id: int):
    applicant = Applicant.objects.get(pk=applicant_id)
    form = ApplicantForm(request.POST or None, instance=applicant)
    if form.is_valid():
        form.save()
        redirect_url = reverse("flow:review", args=[applicant_id])
        return redirect(to=redirect_url)
    return render(
        request,
        "flow/edit_applicant_form.html",
        {"form": form, "applicant_id": applicant_id},
    )


def add_application(request: HttpRequest, applicant_id: int) -> HttpResponse:
    applicant_data = Applicant.objects.get(pk=applicant_id)
    form = ApplicationForm(data=request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.applicant = applicant_data
        obj.save()
        redirect_url = reverse("flow:review", args=[applicant_id])
        return redirect(to=redirect_url)
    return render(request, "flow/add_application_form.html", {"form": form})


def edit_application(request: HttpRequest, applicant_id: int):
    application = (
        Application.objects.filter(applicant_id=applicant_id)
        .order_by("-created_at")
        .first()
    )
    form = ApplicationForm(request.POST or None, instance=application)
    if form.is_valid():
        form.save()
        redirect_url = reverse("flow:review", args=[applicant_id])
        return redirect(to=redirect_url)
    return render(
        request,
        "flow/edit_application_form.html",
        {"form": form, "applicant_id": applicant_id},
    )


def review(request: HttpRequest, applicant_id: int) -> HttpResponse:
    applicant = Applicant.objects.get(pk=applicant_id)
    application = (
        Application.objects.filter(applicant_id=applicant_id)
        .order_by("-created_at")
        .first()
    )
    form = ConsentForm(data=request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.applicant = applicant
        obj.save()
        return redirect(to="flow:confirmation")
    return render(
        request,
        "flow/review.html",
        {"form": form, "applicant": applicant, "application": application},
    )


def confirmation(request: HttpRequest) -> HttpResponse:
    return render(request, template_name="flow/confirmation.html")

src/renard/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index(request: HttpRequest) -> HttpResponse:
    return render(request, template_name="index.html")

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta name="description"
              content="Submit German long-term care applications.">
        <meta name="keywords" content="care,application,renard">
        <meta charset="utf-8"
              name="viewport"
              content="width=device-width, initial-scale=1">
        <title>Renard</title>
        <!-- Latest compiled and minified CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
              crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
                crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                {% block body_block %}
                {% endblock body_block %}
            </div>
        </div>
    </body>
</html>

src/templates/flow/add_applicant_form.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <div class="container pt-5 mt-5">
        <div class="flex flex-col space-y-4 text-center">
            <h2 class="mx-auto my-2 max-w-md text-2xl font-medium tracking-tight md:text-3xl">
                Bitte tragen Sie Ihre persönlichen Daten ein.
            </h2>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-dark" value="Weiter">
            </form>
        </div>
    </div>
{% endblock body_block %}

src/templates/flow/add_application_form.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <div class="container pt-5 mt-5">
        <div class="flex flex-col space-y-4 text-center">
            <h2 class="mx-auto my-2 max-w-md text-2xl font-medium tracking-tight md:text-3xl">
                Bitte wählen Sie aus, welchen Antrag Sie stellen möchten.
            </h2>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-dark" value="Weiter">
            </form>
        </div>
    </div>
{% endblock body_block %}

src/templates/flow/confirmation.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block body_block %}
    <div class="container pt-5 mt-5">
        <div class="flex flex-col space-y-4 text-center">
            <h2 class="mx-auto my-2 max-w-md text-2xl font-medium tracking-tight md:text-3xl">Alles erledigt.</h2>
            <p>
                Ihr Antrag wurde eingereicht.
                <br>
                In den nächsten Tagen meldet sich ein Gutachter bei Ihnen,
                um einen persönlichen Termin zu vereinbaren.
            </p>
        </div>
    </div>
    <div class="container" id="info">
        <div class="row pt-4">
            <div class="col-12">
                <div class="flex flex-col space-y-4 text-center">
                    <p>Bitte beachten Sie diese weiteren Informationen zu Ihrer Pflege:</p>
                    <p>
                        <a href="https://www.google.de/" target="_blank">Pflege-Checkliste</a>
                    </p>
                    <p>
                        <a href="https://www.google.de/" target="_blank">Informationsblatt zur Pflege</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock body_block %}

src/templates/flow/edit_applicant_form.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <h1 class="display-4">Bearbeiten Sie Ihre Daten</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-dark" value="Update">
    </form>
    <br>
{% endblock body_block %}

src/templates/flow/edit_application_form.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <h1 class="display-4">Bearbeiten Sie Ihre Antrags-Daten</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-dark" value="Update">
    </form>
    <br>
{% endblock body_block %}

src/templates/flow/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block body_block %}
    <div class="container pt-5 mt-5">
        <div class="flex flex-col space-y-4 text-center">
            <h2 class="mx-auto my-2 max-w-md text-2xl font-medium tracking-tight md:text-3xl">Online-Antrag.</h2>
            <p>Reichen Sie einen digitalen Pflegeantrag ein.</p>
            <button class="btn btn-dark m-1"
                    onclick="location.href='{% url 'flow:add_applicant' %}'"
                    name='start'
                    type="submit">Antrag starten</button>
        </div>
    </div>
{% endblock body_block %}

src/templates/flow/review.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <div class="container pt-5 mt-5">
        <div class="flex flex-col space-y-4 text-center">
            <h2 class="mx-auto my-2 max-w-md text-2xl font-medium tracking-tight md:text-3xl">
                Bitte überprüfen und bestätigen Sie Ihre Angaben.
            </h2>
        </div>
    </div>
    <div class="container pt-1 mt-5" id="applicant">
        <div class="row pt-1">
            <div class="col-12">
                <div class="accordion" id="accordionMainApplicant">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingMainApplicant">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapseMainApplicant"
                                    aria-expanded="false"
                                    aria-controls="collapseMainApplicant">Ihre persönlichen Angaben</button>
                        </h2>
                        <div id="collapseMainApplicant"
                             class="accordion-collapse collapse"
                             aria-labelledby="headingMainApplicant"
                             data-bs-parent="#accordionMainApplicant">
                            <div class="accordion-body">
                                <div class="ms-2 me-auto">
                                    <div>
                                        Name: <i>{{ applicant.first_name }}, {{ applicant.last_name }}</i>
                                    </div>
                                    <div>
                                        Versicherungsnummer: <i>{{ applicant.insurance_number }}</i>
                                    </div>
                                    <div>
                                        Geburtsdatum: <i>{{ applicant.birth_date|date:"d.m.Y" }}</i>
                                    </div>
                                    <div>
                                        Addresse: <i>{{ applicant.street_number }}, {{ applicant.zip_code }} {{ applicant.city }}</i>
                                    </div>
                                    <div>
                                        Telefonnummer: <i>{{ applicant.phonenumber }}</i>
                                    </div>
                                    <div>
                                        Email-Adresse: <i>{{ applicant.email }}</i>
                                    </div>
                                    <button class="btn btn-dark m-1"
                                            onclick="location.href='{% url 'flow:edit_applicant' applicant.id %}'"
                                            type="submit">Bearbeiten</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container pt-1 mt-1" id="application">
        <div class="row pt-1">
            <div class="col-12">
                <div class="accordion" id="accordionMainApplication">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingMainApplication">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapseMainApplication"
                                    aria-expanded="false"
                                    aria-controls="collapseMainApplication">Ihre Antrags-Daten</button>
                        </h2>
                        <div id="collapseMainApplication"
                             class="accordion-collapse collapse"
                             aria-labelledby="headingMainApplication"
                             data-bs-parent="#accordionMainApplication">
                            <div class="accordion-body">
                                <div class="ms-2 me-auto">
                                    <div>
                                        Erstantrag:
                                        {% if application.first_application %}
                                            <i>Ich beantrage einen Erstantrag.</i>
                                        {% else %}
                                            <i>Ich beantrage einen Wiederholungsantrag.</i>
                                        {% endif %}
                                    </div>
                                    <div>
                                        Leistungen, die beantragt werden sollen:
                                        <ul>
                                            {% for service in application.selected_services %}
                                                <li>
                                                    {% for value, label in application.SERVICE_OPTIONS %}
                                                        {% if service == value %}<i>{{ label }}</i>{% endif %}
                                                    {% endfor %}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <button class="btn btn-dark m-1"
                                            onclick="location.href='{% url 'flow:edit_application' applicant.id %}'"
                                            type="submit">Bearbeiten</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container" id="consent">
        <div class="flex flex-col space-y-4 text-center">
            <div class="row pt-4">
                <div class="col-12">
                    <form method="post">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <a href="https://www.google.de/" target="_blank">Schweigepflichtentbindung & Einwilligungserklärung</a>
                        <br>
                        <br>
                        <input type="submit" class="btn btn-dark" value="Antrag abschicken">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body_block %}

src/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block body_block %}
    <div class="container pt-5 mt-5">
        <div class="flex flex-col space-y-4 text-center">
            <h2 class="mx-auto my-2 max-w-md text-2xl font-medium tracking-tight md:text-3xl">Online-Antrag.</h2>
            <p>Reichen Sie einen digitalen Pflegeantrag ein.</p>
            <button class="btn btn-dark m-1"
                    onclick="location.href='{% url 'flow:add_applicant' %}'"
                    name='start'
                    type="submit">Antrag starten</button>
        </div>
    </div>
{% endblock body_block %}